[General]
all-hybrid = false
allow-dns-svcb = false
allow-hotspot-access = false
allow-wifi-access = false
# always-raw-tcp-hosts = 
# always-raw-tcp-keywords = 
# always-real-ip = 
auto-suspend = true
block-quic = per-policy
compatibility-mode = 3
debug-cpu-usage = false
debug-memory-usage = false
disable-geoip-db-auto-update = false
dns-server = 223.5.5.5, 119.29.29.29
encrypted-dns-follow-outbound-mode = false
# encrypted-dns-server = 
encrypted-dns-skip-cert-verification = false
exclude-simple-hostnames = false
# external-controller-access = mmwwjl@127.0.0.1:6170
# force-http-engine-hosts = 
gateway-restricted-to-lan = true
# geoip-maxmind-url = 
hide-vpn-icon = false
hijack-dns = *:53
# http-api = mmwwjl@127.0.0.1:6171
http-api-tls = false
http-api-web-dashboard = false
icmp-forwarding = true
include-all-networks = false
include-apns = false
include-cellular-services = false
include-local-networks = false
internet-test-url = http://connectivitycheck.gstatic.com/generate_204
ipv6 = false
ipv6-vif = off
loglevel = notify
proxy-restricted-to-lan = true
# proxy-test-udp = 
proxy-test-url = http://cp.cloudflare.com/generate_204
show-error-page = true
show-error-page-for-reject = true
# skip-proxy = 
test-timeout = 3
# tun-excluded-routes = 
# tun-included-routes = 
udp-policy-not-supported-behaviour = REJECT
udp-priority = false
use-local-host-item-for-proxy = false
# wifi-access-http-auth = yhmwwl:mmwywl
# wifi-access-http-port = 6152
# wifi-access-socks5-port = 6153
wifi-assist = false
full-header-mode = false
use-default-policy-if-wifi-not-primary = false
read-etc-hosts = false
# http-listen = 0.0.0.0:6152
# socks5-listen = 0.0.0.0:6153
