allow-lan: false
bind-address: "*"
lan-allowed-ips: []
lan-disallowed-ips: []

authentication: []
skip-auth-prefixes: []

mode: rule

log-level: warning

ipv6: false

keep-alive-interval: 30
keep-alive-idle: 180
disable-keep-alive: false

find-process-mode: strict

# external-controller: 127.0.0.1:9090
# external-controller-cors:
#   allow-origins: ["*"]
#   allow-private-network: true
# secret: ""

# external-ui: ./external-ui

# external-ui-name: metacubexd

# external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

profile:
  store-selected: true
  store-fake-ip: true

unified-delay: true

tcp-concurrent: false

# interface-name: eth0

# routing-mark: 6666

geodata-mode: false

geodata-loader: memconservative

geo-auto-update: true
geo-update-interval: 24

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/v2fly/domain-list-community@release/dlc.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-without-asn.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"

global-ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

etag-support: true

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  listen: 127.0.0.1:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - RULE-SET,fake-ip-filter,real-ip
    - MATCH,fake-ip
  fake-ip-filter-mode: rule
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  default-nameserver: [223.6.6.6, 119.29.29.29]
  nameserver-policy:
    "rule-set:direct-private-domain": [system]
    "rule-set:final-direct-domain": [https://dns.alidns.com/dns-query, https://doh.pub/dns-query]
  proxy-server-nameserver: [https://dns.alidns.com/dns-query, https://doh.pub/dns-query]
  direct-nameserver: []
  direct-nameserver-follow-policy: false
  nameserver: [https://dns.alidns.com/dns-query, https://cloudflare-dns.com/dns-query]
  fallback: []
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite: []
    ipcidr: [240.0.0.0/4]
    domain: []

# port: 7890
# socks-port: 7891
mixed-port: 7892
# redir-port: 7893
# tproxy-port: 7894

tun:
  enable: true
  stack: mixed
  device: aether
  auto-route: true
  # auto-redirect: true
  auto-detect-interface: true
  dns-hijack: [any:53]
  strict-route: true
  mtu: 1480
  # gso: true
  # gso-max-size: 65536
  udp-timeout: 300
  iproute2-table-index: 2022
  iproute2-rule-index: 9000
  endpoint-independent-nat: false

ntp:
  enable: true
  write-to-system: false
  server: ntp.aliyun.com
  port: 123
  interval: 30

proxies:

proxies-custom-hk: &proxies-custom-hk []
proxies-custom-jp: &proxies-custom-jp []
proxies-custom-us: &proxies-custom-us []

proxy-group-custom: &proxy-group-custom
  type: select

proxy-group-region: &proxy-group-region
  type: select
  include-all-proxies: true

proxy-groups:
  - name: YouTube
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/youtube.svg

  - name: Telegram
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/telegram.svg

  - name: Game
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/steam.svg

  - name: Video
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/netflix.svg

  - name: AI
    <<: *proxy-group-custom
    proxies: *proxies-custom-us
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/openai.svg

  - name: Crypto
    <<: *proxy-group-custom
    proxies: *proxies-custom-jp
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/binance.svg

  - name: Finance
    <<: *proxy-group-custom
    proxies: *proxies-custom-us
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/paypal.svg

  - name: Ecommerce
    <<: *proxy-group-custom
    proxies: *proxies-custom-us
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/amazon.svg

  - name: Google
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/google.svg

  - name: Microsoft
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/microsoft.svg

  - name: Apple
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/apple.svg

  - name: Proxy
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/policies/svg/proxy.svg

  - name: HK
    <<: *proxy-group-region
    filter: HK
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/hk.svg

  - name: JP
    <<: *proxy-group-region
    filter: JP
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/jp.svg

  - name: US
    <<: *proxy-group-region
    filter: US
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/us.svg

rule-provider-domain: &rule-provider-domain
  type: http
  interval: 86400
  behavior: domain
  format: mrs

rule-provider-ipcidr: &rule-provider-ipcidr
  type: http
  interval: 86400
  behavior: ipcidr
  format: mrs

rule-provider-classical: &rule-provider-classical
  type: http
  interval: 86400
  behavior: classical

rule-providers:
  fake-ip-filter:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/fake-ip-filter.mrs
    path: ./rulesets/fake-ip-filter.mrs

  direct-private-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-private-domain.mrs
    path: ./rulesets/direct-private-domain.mrs

  direct-private-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-private-ipcidr.mrs
    path: ./rulesets/direct-private-ipcidr.mrs

  direct-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-domain.mrs
    path: ./rulesets/direct-domain.mrs

  direct-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/direct-classical.yaml
    path: ./rulesets/direct-classical.yaml

  reject-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/reject-domain.mrs
    path: ./rulesets/reject-domain.mrs

  reject-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/reject-classical.yaml
    path: ./rulesets/reject-classical.yaml

  youtube-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/youtube-domain.mrs
    path: ./rulesets/youtube-domain.mrs

  bilibili-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/bilibili-domain.mrs
    path: ./rulesets/bilibili-domain.mrs

  tiktok-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/tiktok-domain.mrs
    path: ./rulesets/tiktok-domain.mrs

  spotify-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/spotify-domain.mrs
    path: ./rulesets/spotify-domain.mrs

  telegram-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/telegram-classical.yaml
    path: ./rulesets/telegram-classical.yaml

  github-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/github-classical.yaml
    path: ./rulesets/github-classical.yaml

  speedtest-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/speedtest-domain.mrs
    path: ./rulesets/speedtest-domain.mrs

  nike-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/nike-classical.yaml
    path: ./rulesets/nike-classical.yaml

  game-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/game-cn-domain.mrs
    path: ./rulesets/game-cn-domain.mrs

  game-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/game-domain.mrs
    path: ./rulesets/game-domain.mrs

  video-netflix-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/video-netflix-domain.mrs
    path: ./rulesets/video-netflix-domain.mrs

  video-netflix-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/video-netflix-ipcidr.mrs
    path: ./rulesets/video-netflix-ipcidr.mrs

  video-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/video-domain.mrs
    path: ./rulesets/video-domain.mrs

  ai-apple-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ai-apple-domain.mrs
    path: ./rulesets/ai-apple-domain.mrs

  ai-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ai-domain.mrs
    path: ./rulesets/ai-domain.mrs

  crypto-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/crypto-domain.mrs
    path: ./rulesets/crypto-domain.mrs

  finance-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/finance-domain.mrs
    path: ./rulesets/finance-domain.mrs

  ecommerce-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ecommerce-domain.mrs
    path: ./rulesets/ecommerce-domain.mrs

  ecommerce-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ecommerce-ipcidr.mrs
    path: ./rulesets/ecommerce-ipcidr.mrs

  google-voice-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/google-voice-domain.mrs
    path: ./rulesets/google-voice-domain.mrs

  google-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/google-cn-domain.mrs
    path: ./rulesets/google-cn-domain.mrs

  google-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/google-domain.mrs
    path: ./rulesets/google-domain.mrs

  google-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/google-ipcidr.mrs
    path: ./rulesets/google-ipcidr.mrs

  microsoft-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/microsoft-cn-domain.mrs
    path: ./rulesets/microsoft-cn-domain.mrs

  microsoft-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/microsoft-domain.mrs
    path: ./rulesets/microsoft-domain.mrs

  apple-proxy-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apple-proxy-domain.mrs
    path: ./rulesets/apple-proxy-domain.mrs

  apple-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apple-cn-domain.mrs
    path: ./rulesets/apple-cn-domain.mrs

  apple-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apple-domain.mrs
    path: ./rulesets/apple-domain.mrs

  apple-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apple-ipcidr.mrs
    path: ./rulesets/apple-ipcidr.mrs

  final-direct-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/final-direct-domain.mrs
    path: ./rulesets/final-direct-domain.mrs

  final-direct-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/final-direct-ipcidr.mrs
    path: ./rulesets/final-direct-ipcidr.mrs

rules:
  - RULE-SET,direct-private-domain,DIRECT
  - RULE-SET,direct-private-ipcidr,DIRECT,no-resolve
  - RULE-SET,direct-domain,DIRECT
  - RULE-SET,direct-classical,DIRECT
  - RULE-SET,reject-domain,REJECT
  - RULE-SET,reject-classical,REJECT
  - RULE-SET,youtube-domain,YouTube
  - RULE-SET,bilibili-domain,DIRECT
  - RULE-SET,tiktok-domain,US
  - RULE-SET,spotify-domain,US
  - RULE-SET,telegram-classical,Telegram
  - RULE-SET,github-classical,HK
  - RULE-SET,speedtest-domain,DIRECT
  - RULE-SET,nike-classical,US
  - RULE-SET,game-cn-domain,DIRECT
  - RULE-SET,game-domain,Game
  - RULE-SET,video-netflix-domain,Video
  - RULE-SET,video-netflix-ipcidr,Video,no-resolve
  - RULE-SET,video-domain,Video
  - RULE-SET,ai-apple-domain,US
  - RULE-SET,ai-domain,AI
  - RULE-SET,crypto-domain,Crypto
  - RULE-SET,finance-domain,Finance
  - RULE-SET,ecommerce-domain,Ecommerce
  - RULE-SET,ecommerce-ipcidr,Ecommerce,no-resolve
  - RULE-SET,google-voice-domain,US
  - RULE-SET,google-cn-domain,DIRECT
  - RULE-SET,google-domain,Google
  - RULE-SET,google-ipcidr,Google,no-resolve
  - RULE-SET,microsoft-cn-domain,DIRECT
  - RULE-SET,microsoft-domain,Microsoft
  - RULE-SET,apple-proxy-domain,Apple
  - RULE-SET,apple-cn-domain,DIRECT
  - RULE-SET,apple-domain,Apple
  - RULE-SET,apple-ipcidr,Apple,no-resolve
  - RULE-SET,final-direct-domain,DIRECT
  - RULE-SET,final-direct-ipcidr,DIRECT,no-resolve
  - MATCH,Proxy
