allow-lan: false
bind-address: "*"
lan-allowed-ips: []
lan-disallowed-ips: []

authentication: []
skip-auth-prefixes: []

mode: rule

log-level: warning

ipv6: false

keep-alive-interval: 30
keep-alive-idle: 180
disable-keep-alive: false

find-process-mode: strict

external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins: ["*"]
  allow-private-network: false
secret: ""

external-ui: dashboard

external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

profile:
  store-selected: true
  store-fake-ip: true

unified-delay: true

tcp-concurrent: false

geodata-mode: false

geodata-loader: memconservative

geo-auto-update: true
geo-update-interval: 24

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/v2fly/domain-list-community@release/dlc.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-without-asn.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"

global-ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"

etag-support: true

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  listen: 127.0.0.1:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - RULE-SET,fake-ip-filter,real-ip
    - MATCH,fake-ip
  fake-ip-filter-mode: rule
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  default-nameserver: [system]
  nameserver-policy:
    "rule-set:direct-domain": [system]
    "rule-set:final-direct-domain": [https://dns.alidns.com/dns-query, https://doh.pub/dns-query]
  proxy-server-nameserver: [https://dns.alidns.com/dns-query, https://doh.pub/dns-query]
  direct-nameserver: []
  direct-nameserver-follow-policy: false
  nameserver: [https://dns.alidns.com/dns-query, https://cloudflare-dns.com/dns-query]
  fallback: []
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite: []
    ipcidr: [240.0.0.0/4]
    domain: []

# port: 7890
# socks-port: 7891
mixed-port: 7892
# redir-port: 7893
# tproxy-port: 7894

tun:
  enable: true
  stack: mixed
  device: tun0
  auto-route: true
  auto-detect-interface: true
  dns-hijack: [any:53]
  strict-route: true
  mtu: 1440
  udp-timeout: 90
  iproute2-table-index: 2022
  iproute2-rule-index: 9000
  endpoint-independent-nat: false

proxies:

proxies-custom-hk: &proxies-custom-hk []
proxies-custom-jp: &proxies-custom-jp []
proxies-custom-us: &proxies-custom-us []

proxy-group-custom: &proxy-group-custom
  type: select

proxy-group-region: &proxy-group-region
  type: select
  include-all-proxies: true

proxy-groups:
  - name: GAM
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/gam.svg

  - name: VDO
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/vdo.svg

  - name: AIS
    <<: *proxy-group-custom
    proxies: *proxies-custom-us
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/ais.svg

  - name: CEX
    <<: *proxy-group-custom
    proxies: *proxies-custom-jp
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/cex.svg

  - name: FIN
    <<: *proxy-group-custom
    proxies: *proxies-custom-us
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/fin.svg

  - name: ECM
    <<: *proxy-group-custom
    proxies: *proxies-custom-us
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/ecm.svg

  - name: GGL
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/ggl.svg

  - name: MSF
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/msf.svg

  - name: APL
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/services/svg/apl.svg

  - name: PROXY
    <<: *proxy-group-custom
    proxies: *proxies-custom-hk
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/policies/svg/proxy.svg

  - name: HK
    <<: *proxy-group-region
    filter: HK
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/hk.svg

  - name: JP
    <<: *proxy-group-region
    filter: JP
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/jp.svg

  - name: US
    <<: *proxy-group-region
    filter: US
    icon: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/common/icons/flags/svg/us.svg

rule-provider-domain: &rule-provider-domain
  type: http
  interval: 86400
  behavior: domain
  format: mrs

rule-provider-ipcidr: &rule-provider-ipcidr
  type: http
  interval: 86400
  behavior: ipcidr
  format: mrs

rule-provider-classical: &rule-provider-classical
  type: http
  interval: 86400
  behavior: classical

rule-providers:
  fake-ip-filter:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/fake-ip-filter.mrs
    path: ./rulesets/fake-ip-filter.mrs

  direct-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-domain.mrs
    path: ./rulesets/direct-domain.mrs

  direct-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/direct-ipcidr.mrs
    path: ./rulesets/direct-ipcidr.mrs

  direct-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/direct-classical.yaml
    path: ./rulesets/direct-classical.yaml

  yt-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/yt-domain.mrs
    path: ./rulesets/yt-domain.mrs

  tt-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/tt-domain.mrs
    path: ./rulesets/tt-domain.mrs

  sp-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/sp-domain.mrs
    path: ./rulesets/sp-domain.mrs

  tg-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/tg-ipcidr.mrs
    path: ./rulesets/tg-ipcidr.mrs

  gh-classical:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/gh-classical.yaml
    path: ./rulesets/gh-classical.yaml

  st-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/st-domain.mrs
    path: ./rulesets/st-domain.mrs

  gam-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/gam-cn-domain.mrs
    path: ./rulesets/gam-cn-domain.mrs

  gam-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/gam-domain.mrs
    path: ./rulesets/gam-domain.mrs

  vdo-us-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/vdo-us-domain.mrs
    path: ./rulesets/vdo-us-domain.mrs

  vdo-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/vdo-domain.mrs
    path: ./rulesets/vdo-domain.mrs

  vdo-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/vdo-ipcidr.mrs
    path: ./rulesets/vdo-ipcidr.mrs

  ais-jp-classical:
    <<: *rule-provider-classical
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/merged/ais-jp-classical.yaml
    path: ./rulesets/ais-jp-classical.yaml

  ais-us-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ais-us-domain.mrs
    path: ./rulesets/ais-us-domain.mrs

  ais-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ais-domain.mrs
    path: ./rulesets/ais-domain.mrs

  cex-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/cex-domain.mrs
    path: ./rulesets/cex-domain.mrs

  fin-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/fin-domain.mrs
    path: ./rulesets/fin-domain.mrs

  ecm-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ecm-domain.mrs
    path: ./rulesets/ecm-domain.mrs

  ecm-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ecm-ipcidr.mrs
    path: ./rulesets/ecm-ipcidr.mrs

  ggl-us-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-us-domain.mrs
    path: ./rulesets/ggl-us-domain.mrs

  ggl-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-cn-domain.mrs
    path: ./rulesets/ggl-cn-domain.mrs

  ggl-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-domain.mrs
    path: ./rulesets/ggl-domain.mrs

  ggl-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/ggl-ipcidr.mrs
    path: ./rulesets/ggl-ipcidr.mrs

  msf-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/msf-cn-domain.mrs
    path: ./rulesets/msf-cn-domain.mrs

  msf-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/msf-domain.mrs
    path: ./rulesets/msf-domain.mrs

  apl-ex-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-ex-domain.mrs
    path: ./rulesets/apl-ex-domain.mrs

  apl-cn-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-cn-domain.mrs
    path: ./rulesets/apl-cn-domain.mrs

  apl-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-domain.mrs
    path: ./rulesets/apl-domain.mrs

  apl-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/apl-ipcidr.mrs
    path: ./rulesets/apl-ipcidr.mrs

  final-direct-domain:
    <<: *rule-provider-domain
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/final-direct-domain.mrs
    path: ./rulesets/final-direct-domain.mrs

  final-direct-ipcidr:
    <<: *rule-provider-ipcidr
    url: https://raw.githubusercontent.com/ztyxlv/profiles-proxy/main/mihomo/rules/compiled/final-direct-ipcidr.mrs
    path: ./rulesets/final-direct-ipcidr.mrs

rules:
  - RULE-SET,direct-domain,DIRECT
  - RULE-SET,direct-ipcidr,DIRECT,no-resolve
  - RULE-SET,direct-classical,DIRECT
  - RULE-SET,yt-domain,HK
  - RULE-SET,tt-domain,US
  - RULE-SET,sp-domain,US
  - RULE-SET,tg-ipcidr,HK,no-resolve
  - RULE-SET,gh-classical,HK
  - RULE-SET,st-domain,HK
  - RULE-SET,gam-cn-domain,DIRECT
  - RULE-SET,gam-domain,GAM
  - RULE-SET,vdo-us-domain,US
  - RULE-SET,vdo-domain,VDO
  - RULE-SET,vdo-ipcidr,VDO,no-resolve
  - RULE-SET,ais-jp-classical,JP
  - RULE-SET,ais-us-domain,US
  - RULE-SET,ais-domain,AIS
  - RULE-SET,cex-domain,CEX
  - RULE-SET,fin-domain,FIN
  - RULE-SET,ecm-domain,ECM
  - RULE-SET,ecm-ipcidr,ECM,no-resolve
  - RULE-SET,ggl-us-domain,US
  - RULE-SET,ggl-cn-domain,DIRECT
  - RULE-SET,ggl-domain,GGL
  - RULE-SET,ggl-ipcidr,GGL,no-resolve
  - RULE-SET,msf-cn-domain,DIRECT
  - RULE-SET,msf-domain,MSF
  - RULE-SET,apl-ex-domain,APL
  - RULE-SET,apl-cn-domain,DIRECT
  - RULE-SET,apl-domain,APL
  - RULE-SET,apl-ipcidr,APL,no-resolve
  - RULE-SET,final-direct-domain,DIRECT
  - RULE-SET,final-direct-ipcidr,DIRECT,no-resolve
  - MATCH,PROXY
