[[rename_node]]
match = "^(冰岛|Iceland)"
replace = "🇮🇸 IS 01"

[[rename_node]]
match = "^(挪威|Norway)"
replace = "🇳🇴 NO 01"

[[rename_node]]
match = "^(瑞士|Switzerland)"
replace = "🇨🇭 CH 01"

[[rename_node]]
match = "^(丹麦|Denmark)"
replace = "🇩🇰 DK 01"

[[rename_node]]
match = "^(德国|Germany)"
replace = "🇩🇪 DE 01"

[[rename_node]]
match = "^(瑞典|Sweden)"
replace = "🇸🇪 SE 01"

[[rename_node]]
match = "^(澳大利亚|Australia)"
replace = "🇦🇺 AU 01"

[[rename_node]]
match = "^(中国香港特别行政区|Hong Kong, China \\(SAR\\)|香港)"
replace = "🇭🇰 HK"

[[rename_node]]
match = "^(荷兰|Netherlands)"
replace = "🇳🇱 NL 01"

[[rename_node]]
match = "^(比利时|Belgium)"
replace = "🇧🇪 BE 01"

[[rename_node]]
match = "^(爱尔兰|Ireland)"
replace = "🇮🇪 IE 01"

[[rename_node]]
match = "^(芬兰|Finland)"
replace = "🇫🇮 FI 01"

[[rename_node]]
match = "^(新加坡|Singapore)"
replace = "🇸🇬 SG"

[[rename_node]]
match = "^(英国|United Kingdom)"
replace = "🇬🇧 GB 01"

[[rename_node]]
match = "^(阿拉伯联合酋长国|United Arab Emirates)"
replace = "🇦🇪 AE 01"

[[rename_node]]
match = "^(加拿大|Canada)"
replace = "🇨🇦 CA 01"

[[rename_node]]
match = "^(新西兰|New Zealand)"
replace = "🇳🇿 NZ 01"

[[rename_node]]
match = "^(美国|United States)"
replace = "🇺🇸 US"

[[rename_node]]
match = "^(韩国|Korea \\(Republic of\\))"
replace = "🇰🇷 KR 01"

[[rename_node]]
match = "^(斯洛文尼亚|Slovenia)"
replace = "🇸🇮 SI 01"

[[rename_node]]
match = "^(奥地利|Austria)"
replace = "🇦🇹 AT 01"

[[rename_node]]
match = "^(日本|Japan)"
replace = "🇯🇵 JP"

[[rename_node]]
match = "^(卢森堡|Luxembourg)"
replace = "🇱🇺 LU 01"

[[rename_node]]
match = "^(法国|France)"
replace = "🇫🇷 FR 01"

[[rename_node]]
match = "^(以色列|Israel)"
replace = "🇮🇱 IL 01"

[[rename_node]]
match = "^(西班牙|Spain)"
replace = "🇪🇸 ES 01"

[[rename_node]]
match = "^(意大利|Italy)"
replace = "🇮🇹 IT 01"

[[rename_node]]
match = "^(塞浦路斯|Cyprus)"
replace = "🇨🇾 CY 01"

[[rename_node]]
match = "^(希腊|Greece)"
replace = "🇬🇷 GR 01"

[[rename_node]]
match = "^(波兰|Poland)"
replace = "🇵🇱 PL 01"

[[rename_node]]
match = "^(爱沙尼亚|Estonia)"
replace = "🇪🇪 EE 01"

[[rename_node]]
match = "^(沙特阿拉伯|Saudi Arabia)"
replace = "🇸🇦 SA 01"

[[rename_node]]
match = "^(立陶宛|Lithuania)"
replace = "🇱🇹 LT 01"

[[rename_node]]
match = "^(葡萄牙|Portugal)"
replace = "🇵🇹 PT 01"

[[rename_node]]
match = "^(克罗地亚|Croatia)"
replace = "🇭🇷 HR 01"

[[rename_node]]
match = "^(拉脱维亚|Latvia)"
replace = "🇱🇻 LV 01"

[[rename_node]]
match = "^(卡塔尔|Qatar)"
replace = "🇶🇦 QA 01"

[[rename_node]]
match = "^(斯洛伐克|Slovakia)"
replace = "🇸🇰 SK 01"

[[rename_node]]
match = "^(智利|Chile)"
replace = "🇨🇱 CL 01"

[[rename_node]]
match = "^(阿根廷|Argentina)"
replace = "🇦🇷 AR 01"

[[rename_node]]
match = "^(乌拉圭|Uruguay)"
replace = "🇺🇾 UY 01"

[[rename_node]]
match = "^(阿曼|Oman)"
replace = "🇴🇲 OM 01"

[[rename_node]]
match = "^(土耳其|Türkiye)"
replace = "🇹🇷 TR 01"

[[rename_node]]
match = "^(保加利亚|Bulgaria)"
replace = "🇧🇬 BG 01"

[[rename_node]]
match = "^(罗马尼亚|Romania)"
replace = "🇷🇴 RO 01"

[[rename_node]]
match = "^(格鲁吉亚|Georgia)"
replace = "🇬🇪 GE 01"

[[rename_node]]
match = "^(哈萨克斯坦|Kazakhstan)"
replace = "🇰🇿 KZ 01"

[[rename_node]]
match = "^(哥斯达黎加|Costa Rica)"
replace = "🇨🇷 CR 01"

[[rename_node]]
match = "^(塞尔维亚|Serbia)"
replace = "🇷🇸 RS 01"

[[rename_node]]
match = "^(俄罗斯联邦|Russian Federation|俄罗斯)"
replace = "🇷🇺 RU 01"

[[rename_node]]
match = "^(马来西亚|Malaysia)"
replace = "🇲🇾 MY 01"

[[rename_node]]
match = "^(北马其顿|North Macedonia|马其顿)"
replace = "🇲🇰 MK 01"

[[rename_node]]
match = "^(亚美尼亚|Armenia)"
replace = "🇦🇲 AM 01"

[[rename_node]]
match = "^(阿尔巴尼亚|Albania)"
replace = "🇦🇱 AL 01"

[[rename_node]]
match = "^(泰国|Thailand)"
replace = "🇹🇭 TH 01"

[[rename_node]]
match = "^(秘鲁|Peru)"
replace = "🇵🇪 PE 01"

[[rename_node]]
match = "^(墨西哥|Mexico)"
replace = "🇲🇽 MX 01"

[[rename_node]]
match = "^(哥伦比亚|Colombia)"
replace = "🇨🇴 CO 01"

[[rename_node]]
match = "^(巴西|Brazil)"
replace = "🇧🇷 BR 01"

[[rename_node]]
match = "^(摩尔多瓦共和国|Moldova \\(Republic of\\)|摩尔多瓦)"
replace = "🇲🇩 MD 01"

[[rename_node]]
match = "^(乌克兰|Ukraine)"
replace = "🇺🇦 UA 01"

[[rename_node]]
match = "^(厄瓜多尔|Ecuador)"
replace = "🇪🇨 EC 01"

[[rename_node]]
match = "^(越南|Viet Nam)"
replace = "🇻🇳 VN 01"

[[rename_node]]
match = "^(埃及|Egypt)"
replace = "🇪🇬 EG 01"

[[rename_node]]
match = "^(南非|South Africa)"
replace = "🇿🇦 ZA 01"

[[rename_node]]
match = "^(乌兹别克斯坦|Uzbekistan)"
replace = "🇺🇿 UZ 01"

[[rename_node]]
match = "^(玻利维亚多民族国|Bolivia \\(Plurinational State of\\)|玻利维亚)"
replace = "🇧🇴 BO 01"

[[rename_node]]
match = "^(印度尼西亚|Indonesia)"
replace = "🇮🇩 ID 01"

[[rename_node]]
match = "^(菲律宾|Philippines)"
replace = "🇵🇭 PH 01"

[[rename_node]]
match = "^(摩洛哥|Morocco)"
replace = "🇲🇦 MA 01"

[[rename_node]]
match = "^(伊拉克|Iraq)"
replace = "🇮🇶 IQ 01"

[[rename_node]]
match = "^(孟加拉国|Bangladesh|孟加拉)"
replace = "🇧🇩 BD 01"

[[rename_node]]
match = "^(印度|India)"
replace = "🇮🇳 IN 01"

[[rename_node]]
match = "^(危地马拉|Guatemala)"
replace = "🇬🇹 GT 01"

[[rename_node]]
match = "^(尼泊尔|Nepal)"
replace = "🇳🇵 NP 01"

[[rename_node]]
match = "^(安哥拉|Angola)"
replace = "🇦🇴 AO 01"

[[rename_node]]
match = "^(柬埔寨|Cambodia)"
replace = "🇰🇭 KH 01"

[[rename_node]]
match = "^(尼日利亚|Nigeria)"
replace = "🇳🇬 NG 01"

[[rename_node]]
match = "^(巴基斯坦|Pakistan)"
replace = "🇵🇰 PK 01"

[[rename_node]]
match = "^(台湾|Taiwan)"
replace = "🇹🇼 TW"
