[[rename_node]]
match = "(瑞士|Switzerland)"
replace = "🇨🇭 CH"

[[rename_node]]
match = "(德国|Germany)"
replace = "🇩🇪 DE"

[[rename_node]]
match = "(瑞典|Sweden)"
replace = "🇸🇪 SE"

[[rename_node]]
match = "Australia Sydney"
replace = "🇦🇺 AU-SYD"

[[rename_node]]
match = "(澳大利亚|Australia)"
replace = "🇦🇺 AU"

[[rename_node]]
match = "(中国香港特别行政区|Hong Kong, China \\(SAR\\)|Hong Kong)"
replace = "🇭🇰 HK"

[[rename_node]]
match = "(荷兰|Netherlands)"
replace = "🇳🇱 NL"

[[rename_node]]
match = "(爱尔兰|Ireland)"
replace = "🇮🇪 IE"

[[rename_node]]
match = "(新加坡|Singapore)"
replace = "🇸🇬 SG"

[[rename_node]]
match = "(英国|United Kingdom)"
replace = "🇬🇧 GB"

[[rename_node]]
match = "(阿拉伯联合酋长国|United Arab Emirates)"
replace = "🇦🇪 AE"

[[rename_node]]
match = "(加拿大|Canada)"
replace = "🇨🇦 CA"

[[rename_node]]
match = "USA Los Angeles"
replace = "🇺🇸 US-LAX"

[[rename_node]]
match = "USA San Jose"
replace = "🇺🇸 US-SJC"

[[rename_node]]
match = "USA Seattle"
replace = "🇺🇸 US-SEA"

[[rename_node]]
match = "(美国|United States)"
replace = "🇺🇸 US"

[[rename_node]]
match = "(韩国|Korea \\(Republic of\\)|South Korea|Korea)"
replace = "🇰🇷 KR"

[[rename_node]]
match = "(奥地利|Austria)"
replace = "🇦🇹 AT"

[[rename_node]]
match = "(日本|Japan)"
replace = "🇯🇵 JP"

[[rename_node]]
match = "(法国|France)"
replace = "🇫🇷 FR"

[[rename_node]]
match = "(智利|Chile)"
replace = "🇨🇱 CL"

[[rename_node]]
match = "(匈牙利|Hungary)"
replace = "🇭🇺 HU"

[[rename_node]]
match = "(阿根廷|Argentina)"
replace = "🇦🇷 AR"

[[rename_node]]
match = "(土耳其|Türkiye|Turkey)"
replace = "🇹🇷 TR"

[[rename_node]]
match = "(保加利亚|Bulgaria)"
replace = "🇧🇬 BG"

[[rename_node]]
match = "Russia Moscow"
replace = "🇷🇺 RU"

[[rename_node]]
match = "Russia St\\. Petersburg"
replace = "🇷🇺 RU-LED 01"

[[rename_node]]
match = "(俄罗斯联邦|Russian Federation)"
replace = "🇷🇺 RU"

[[rename_node]]
match = "(巴西|Brazil)"
replace = "🇧🇷 BR"

[[rename_node]]
match = "(印度尼西亚|Indonesia)"
replace = "🇮🇩 ID"

[[rename_node]]
match = "(印度|India)"
replace = "🇮🇳 IN"

[[rename_node]]
match = "(台湾|Taiwan)"
replace = "🇹🇼 TW"
