[[rename_node]]
match = "(冰岛|Iceland)"
replace = "🇮🇸 IS"

[[rename_node]]
match = "(挪威|Norway)"
replace = "🇳🇴 NO"

[[rename_node]]
match = "(瑞士|Switzerland)"
replace = "🇨🇭 CH"

[[rename_node]]
match = "(丹麦|Denmark)"
replace = "🇩🇰 DK"

[[rename_node]]
match = "(德国|Germany)"
replace = "🇩🇪 DE"

[[rename_node]]
match = "(瑞典|Sweden)"
replace = "🇸🇪 SE"

[[rename_node]]
match = "(澳大利亚|Australia)"
replace = "🇦🇺 AU"

[[rename_node]]
match = "(中国香港特别行政区|Hong Kong, China \\(SAR\\))"
replace = "🇭🇰 HK"

[[rename_node]]
match = "(荷兰|Netherlands)"
replace = "🇳🇱 NL"

[[rename_node]]
match = "(比利时|Belgium)"
replace = "🇧🇪 BE"

[[rename_node]]
match = "(爱尔兰|Ireland)"
replace = "🇮🇪 IE"

[[rename_node]]
match = "(芬兰|Finland)"
replace = "🇫🇮 FI"

[[rename_node]]
match = "(新加坡|Singapore)"
replace = "🇸🇬 SG"

[[rename_node]]
match = "(英国|United Kingdom)"
replace = "🇬🇧 GB"

[[rename_node]]
match = "(阿拉伯联合酋长国|United Arab Emirates)"
replace = "🇦🇪 AE"

[[rename_node]]
match = "(加拿大|Canada)"
replace = "🇨🇦 CA"

[[rename_node]]
match = "(列支敦士登|Liechtenstein)"
replace = "🇱🇮 LI"

[[rename_node]]
match = "(新西兰|New Zealand)"
replace = "🇳🇿 NZ"

[[rename_node]]
match = "(美国|United States)"
replace = "🇺🇸 US"

[[rename_node]]
match = "(韩国|Korea \\(Republic of\\))"
replace = "🇰🇷 KR"

[[rename_node]]
match = "(斯洛文尼亚|Slovenia)"
replace = "🇸🇮 SI"

[[rename_node]]
match = "(奥地利|Austria)"
replace = "🇦🇹 AT"

[[rename_node]]
match = "(日本|Japan)"
replace = "🇯🇵 JP"

[[rename_node]]
match = "(马耳他|Malta)"
replace = "🇲🇹 MT"

[[rename_node]]
match = "(卢森堡|Luxembourg)"
replace = "🇱🇺 LU"

[[rename_node]]
match = "(法国|France)"
replace = "🇫🇷 FR"

[[rename_node]]
match = "(以色列|Israel)"
replace = "🇮🇱 IL"

[[rename_node]]
match = "(西班牙|Spain)"
replace = "🇪🇸 ES"

[[rename_node]]
match = "(捷克|Czechia)"
replace = "🇨🇿 CZ"

[[rename_node]]
match = "(意大利|Italy)"
replace = "🇮🇹 IT"

[[rename_node]]
match = "(圣马力诺|San Marino)"
replace = "🇸🇲 SM"

[[rename_node]]
match = "(安道尔|Andorra)"
replace = "🇦🇩 AD"

[[rename_node]]
match = "(塞浦路斯|Cyprus)"
replace = "🇨🇾 CY"

[[rename_node]]
match = "(希腊|Greece)"
replace = "🇬🇷 GR"

[[rename_node]]
match = "(波兰|Poland)"
replace = "🇵🇱 PL"

[[rename_node]]
match = "(爱沙尼亚|Estonia)"
replace = "🇪🇪 EE"

[[rename_node]]
match = "(沙特阿拉伯|Saudi Arabia)"
replace = "🇸🇦 SA"

[[rename_node]]
match = "(巴林|Bahrain)"
replace = "🇧🇭 BH"

[[rename_node]]
match = "(立陶宛|Lithuania)"
replace = "🇱🇹 LT"

[[rename_node]]
match = "(葡萄牙|Portugal)"
replace = "🇵🇹 PT"

[[rename_node]]
match = "(克罗地亚|Croatia)"
replace = "🇭🇷 HR"

[[rename_node]]
match = "(拉脱维亚|Latvia)"
replace = "🇱🇻 LV"

[[rename_node]]
match = "(卡塔尔|Qatar)"
replace = "🇶🇦 QA"

[[rename_node]]
match = "(斯洛伐克|Slovakia)"
replace = "🇸🇰 SK"

[[rename_node]]
match = "(智利|Chile)"
replace = "🇨🇱 CL"

[[rename_node]]
match = "(匈牙利|Hungary)"
replace = "🇭🇺 HU"

[[rename_node]]
match = "(阿根廷|Argentina)"
replace = "🇦🇷 AR"

[[rename_node]]
match = "(黑山|Montenegro)"
replace = "🇲🇪 ME"

[[rename_node]]
match = "(乌拉圭|Uruguay)"
replace = "🇺🇾 UY"

[[rename_node]]
match = "(阿曼|Oman)"
replace = "🇴🇲 OM"

[[rename_node]]
match = "(土耳其|Türkiye)"
replace = "🇹🇷 TR"

[[rename_node]]
match = "(科威特|Kuwait)"
replace = "🇰🇼 KW"

[[rename_node]]
match = "(安提瓜和巴布达|Antigua and Barbuda)"
replace = "🇦🇬 AG"

[[rename_node]]
match = "(塞舌尔|Seychelles)"
replace = "🇸🇨 SC"

[[rename_node]]
match = "(保加利亚|Bulgaria)"
replace = "🇧🇬 BG"

[[rename_node]]
match = "(罗马尼亚|Romania)"
replace = "🇷🇴 RO"

[[rename_node]]
match = "(格鲁吉亚|Georgia)"
replace = "🇬🇪 GE"

[[rename_node]]
match = "(圣基茨和尼维斯|Saint Kitts and Nevis)"
replace = "🇰🇳 KN"

[[rename_node]]
match = "(巴拿马|Panama)"
replace = "🇵🇦 PA"

[[rename_node]]
match = "(文莱达鲁萨兰国|Brunei Darussalam)"
replace = "🇧🇳 BN"

[[rename_node]]
match = "(哈萨克斯坦|Kazakhstan)"
replace = "🇰🇿 KZ"

[[rename_node]]
match = "(哥斯达黎加|Costa Rica)"
replace = "🇨🇷 CR"

[[rename_node]]
match = "(塞尔维亚|Serbia)"
replace = "🇷🇸 RS"

[[rename_node]]
match = "(俄罗斯联邦|Russian Federation)"
replace = "🇷🇺 RU"

[[rename_node]]
match = "(白俄罗斯|Belarus)"
replace = "🇧🇾 BY"

[[rename_node]]
match = "(巴哈马|Bahamas)"
replace = "🇧🇸 BS"

[[rename_node]]
match = "(马来西亚|Malaysia)"
replace = "🇲🇾 MY"

[[rename_node]]
match = "(北马其顿|North Macedonia)"
replace = "🇲🇰 MK"

[[rename_node]]
match = "(亚美尼亚|Armenia)"
replace = "🇦🇲 AM"

[[rename_node]]
match = "(巴巴多斯|Barbados)"
replace = "🇧🇧 BB"

[[rename_node]]
match = "(阿尔巴尼亚|Albania)"
replace = "🇦🇱 AL"

[[rename_node]]
match = "(特立尼达和多巴哥|Trinidad and Tobago)"
replace = "🇹🇹 TT"

[[rename_node]]
match = "(毛里求斯|Mauritius)"
replace = "🇲🇺 MU"

[[rename_node]]
match = "(波斯尼亚和黑塞哥维那|Bosnia and Herzegovina)"
replace = "🇧🇦 BA"

[[rename_node]]
match = "(伊朗|Iran \\(Islamic Republic of\\))"
replace = "🇮🇷 IR"

[[rename_node]]
match = "(圣文森特和格林纳丁斯|Saint Vincent and the Grenadines)"
replace = "🇻🇨 VC"

[[rename_node]]
match = "(泰国|Thailand)"
replace = "🇹🇭 TH"

[[rename_node]]
match = "(中国|China)"
replace = "🇨🇳 CN"

[[rename_node]]
match = "(秘鲁|Peru)"
replace = "🇵🇪 PE"

[[rename_node]]
match = "(格林纳达|Grenada)"
replace = "🇬🇩 GD"

[[rename_node]]
match = "(阿塞拜疆|Azerbaijan)"
replace = "🇦🇿 AZ"

[[rename_node]]
match = "(墨西哥|Mexico)"
replace = "🇲🇽 MX"

[[rename_node]]
match = "(哥伦比亚|Colombia)"
replace = "🇨🇴 CO"

[[rename_node]]
match = "(巴西|Brazil)"
replace = "🇧🇷 BR"

[[rename_node]]
match = "(帕劳|Palau)"
replace = "🇵🇼 PW"

[[rename_node]]
match = "(摩尔多瓦共和国|Moldova \\(Republic of\\))"
replace = "🇲🇩 MD"

[[rename_node]]
match = "(乌克兰|Ukraine)"
replace = "🇺🇦 UA"

[[rename_node]]
match = "(厄瓜多尔|Ecuador)"
replace = "🇪🇨 EC"

[[rename_node]]
match = "(多米尼加共和国|Dominican Republic)"
replace = "🇩🇴 DO"

[[rename_node]]
match = "(圭亚那|Guyana)"
replace = "🇬🇾 GY"

[[rename_node]]
match = "(斯里兰卡|Sri Lanka)"
replace = "🇱🇰 LK"

[[rename_node]]
match = "(汤加|Tonga)"
replace = "🇹🇴 TO"

[[rename_node]]
match = "(马尔代夫|Maldives)"
replace = "🇲🇻 MV"

[[rename_node]]
match = "(越南|Viet Nam)"
replace = "🇻🇳 VN"

[[rename_node]]
match = "(土库曼斯坦|Turkmenistan)"
replace = "🇹🇲 TM"

[[rename_node]]
match = "(阿尔及利亚|Algeria)"
replace = "🇩🇿 DZ"

[[rename_node]]
match = "(古巴|Cuba)"
replace = "🇨🇺 CU"

[[rename_node]]
match = "(多米尼加|Dominica)"
replace = "🇩🇲 DM"

[[rename_node]]
match = "(巴拉圭|Paraguay)"
replace = "🇵🇾 PY"

[[rename_node]]
match = "(埃及|Egypt)"
replace = "🇪🇬 EG"

[[rename_node]]
match = "(约旦|Jordan)"
replace = "🇯🇴 JO"

[[rename_node]]
match = "(黎巴嫩|Lebanon)"
replace = "🇱🇧 LB"

[[rename_node]]
match = "(圣卢西亚|Saint Lucia)"
replace = "🇱🇨 LC"

[[rename_node]]
match = "(蒙古|Mongolia)"
replace = "🇲🇳 MN"

[[rename_node]]
match = "(突尼斯|Tunisia)"
replace = "🇹🇳 TN"

[[rename_node]]
match = "(南非|South Africa)"
replace = "🇿🇦 ZA"

[[rename_node]]
match = "(乌兹别克斯坦|Uzbekistan)"
replace = "🇺🇿 UZ"

[[rename_node]]
match = "(玻利维亚多民族国|Bolivia \\(Plurinational State of\\))"
replace = "🇧🇴 BO"

[[rename_node]]
match = "(加蓬|Gabon)"
replace = "🇬🇦 GA"

[[rename_node]]
match = "(马绍尔群岛|Marshall Islands)"
replace = "🇲🇭 MH"

[[rename_node]]
match = "(博茨瓦纳|Botswana)"
replace = "🇧🇼 BW"

[[rename_node]]
match = "(斐济|Fiji)"
replace = "🇫🇯 FJ"

[[rename_node]]
match = "(印度尼西亚|Indonesia)"
replace = "🇮🇩 ID"

[[rename_node]]
match = "(苏里南|Suriname)"
replace = "🇸🇷 SR"

[[rename_node]]
match = "(伯利兹|Belize)"
replace = "🇧🇿 BZ"

[[rename_node]]
match = "(利比亚|Libya)"
replace = "🇱🇾 LY"

[[rename_node]]
match = "(牙买加|Jamaica)"
replace = "🇯🇲 JM"

[[rename_node]]
match = "(吉尔吉斯斯坦|Kyrgyzstan)"
replace = "🇰🇬 KG"

[[rename_node]]
match = "(菲律宾|Philippines)"
replace = "🇵🇭 PH"

[[rename_node]]
match = "(摩洛哥|Morocco)"
replace = "🇲🇦 MA"

[[rename_node]]
match = "(委内瑞拉玻利瓦尔共和国|Venezuela \\(Bolivarian Republic of\\))"
replace = "🇻🇪 VE"

[[rename_node]]
match = "(萨摩亚|Samoa)"
replace = "🇼🇸 WS"

[[rename_node]]
match = "(尼加拉瓜|Nicaragua)"
replace = "🇳🇮 NI"

[[rename_node]]
match = "(瑙鲁|Nauru)"
replace = "🇳🇷 NR"

[[rename_node]]
match = "(不丹|Bhutan)"
replace = "🇧🇹 BT"

[[rename_node]]
match = "(斯威士兰王国|Eswatini \\(Kingdom of\\))"
replace = "🇸🇿 SZ"

[[rename_node]]
match = "(伊拉克|Iraq)"
replace = "🇮🇶 IQ"

[[rename_node]]
match = "(塔吉克斯坦|Tajikistan)"
replace = "🇹🇯 TJ"

[[rename_node]]
match = "(图瓦卢|Tuvalu)"
replace = "🇹🇻 TV"

[[rename_node]]
match = "(孟加拉国|Bangladesh)"
replace = "🇧🇩 BD"

[[rename_node]]
match = "(印度|India)"
replace = "🇮🇳 IN"

[[rename_node]]
match = "(萨尔瓦多|El Salvador)"
replace = "🇸🇻 SV"

[[rename_node]]
match = "(赤道几内亚|Equatorial Guinea)"
replace = "🇬🇶 GQ"

[[rename_node]]
match = "(巴勒斯坦国|Palestine, State of)"
replace = "🇵🇸 PS"

[[rename_node]]
match = "(佛得角|Cabo Verde)"
replace = "🇨🇻 CV"

[[rename_node]]
match = "(纳米比亚|Namibia)"
replace = "🇳🇦 NA"

[[rename_node]]
match = "(危地马拉|Guatemala)"
replace = "🇬🇹 GT"

[[rename_node]]
match = "(刚果|Congo)"
replace = "🇨🇬 CG"

[[rename_node]]
match = "(洪都拉斯|Honduras)"
replace = "🇭🇳 HN"

[[rename_node]]
match = "(基里巴斯|Kiribati)"
replace = "🇰🇮 KI"

[[rename_node]]
match = "(圣多美和普林西比|Sao Tome and Principe)"
replace = "🇸🇹 ST"

[[rename_node]]
match = "(东帝汶|Timor-Leste)"
replace = "🇹🇱 TL"

[[rename_node]]
match = "(加纳|Ghana)"
replace = "🇬🇭 GH"

[[rename_node]]
match = "(肯尼亚|Kenya)"
replace = "🇰🇪 KE"

[[rename_node]]
match = "(尼泊尔|Nepal)"
replace = "🇳🇵 NP"

[[rename_node]]
match = "(瓦努阿图|Vanuatu)"
replace = "🇻🇺 VU"

[[rename_node]]
match = "(老挝人民民主共和国|Lao People's Democratic Republic)"
replace = "🇱🇦 LA"

[[rename_node]]
match = "(安哥拉|Angola)"
replace = "🇦🇴 AO"

[[rename_node]]
match = "(密克罗尼西亚联邦|Micronesia \\(Federated States of\\))"
replace = "🇫🇲 FM"

[[rename_node]]
match = "(缅甸|Myanmar)"
replace = "🇲🇲 MM"

[[rename_node]]
match = "(柬埔寨|Cambodia)"
replace = "🇰🇭 KH"

[[rename_node]]
match = "(科摩罗|Comoros)"
replace = "🇰🇲 KM"

[[rename_node]]
match = "(津巴布韦|Zimbabwe)"
replace = "🇿🇼 ZW"

[[rename_node]]
match = "(赞比亚|Zambia)"
replace = "🇿🇲 ZM"

[[rename_node]]
match = "(喀麦隆|Cameroon)"
replace = "🇨🇲 CM"

[[rename_node]]
match = "(所罗门群岛|Solomon Islands)"
replace = "🇸🇧 SB"

[[rename_node]]
match = "(科特迪瓦|Côte d'Ivoire)"
replace = "🇨🇮 CI"

[[rename_node]]
match = "(乌干达|Uganda)"
replace = "🇺🇬 UG"

[[rename_node]]
match = "(卢旺达|Rwanda)"
replace = "🇷🇼 RW"

[[rename_node]]
match = "(巴布亚新几内亚|Papua New Guinea)"
replace = "🇵🇬 PG"

[[rename_node]]
match = "(多哥|Togo)"
replace = "🇹🇬 TG"

[[rename_node]]
match = "(阿拉伯叙利亚共和国|Syrian Arab Republic)"
replace = "🇸🇾 SY"

[[rename_node]]
match = "(毛里塔尼亚|Mauritania)"
replace = "🇲🇷 MR"

[[rename_node]]
match = "(尼日利亚|Nigeria)"
replace = "🇳🇬 NG"

[[rename_node]]
match = "(坦桑尼亚|Tanzania \\(United Republic of\\))"
replace = "🇹🇿 TZ"

[[rename_node]]
match = "(海地|Haiti)"
replace = "🇭🇹 HT"

[[rename_node]]
match = "(莱索托|Lesotho)"
replace = "🇱🇸 LS"

[[rename_node]]
match = "(巴基斯坦|Pakistan)"
replace = "🇵🇰 PK"

[[rename_node]]
match = "(塞内加尔|Senegal)"
replace = "🇸🇳 SN"

[[rename_node]]
match = "(冈比亚|Gambia)"
replace = "🇬🇲 GM"

[[rename_node]]
match = "(刚果民主共和国|Congo \\(Democratic Republic of the\\))"
replace = "🇨🇩 CD"

[[rename_node]]
match = "(马拉维|Malawi)"
replace = "🇲🇼 MW"

[[rename_node]]
match = "(贝宁|Benin)"
replace = "🇧🇯 BJ"

[[rename_node]]
match = "(几内亚比绍|Guinea-Bissau)"
replace = "🇬🇼 GW"

[[rename_node]]
match = "(吉布提|Djibouti)"
replace = "🇩🇯 DJ"

[[rename_node]]
match = "(苏丹|Sudan)"
replace = "🇸🇩 SD"

[[rename_node]]
match = "(利比里亚|Liberia)"
replace = "🇱🇷 LR"

[[rename_node]]
match = "(厄立特里亚|Eritrea)"
replace = "🇪🇷 ER"

[[rename_node]]
match = "(几内亚|Guinea)"
replace = "🇬🇳 GN"

[[rename_node]]
match = "(埃塞俄比亚|Ethiopia)"
replace = "🇪🇹 ET"

[[rename_node]]
match = "(阿富汗|Afghanistan)"
replace = "🇦🇫 AF"

[[rename_node]]
match = "(莫桑比克|Mozambique)"
replace = "🇲🇿 MZ"

[[rename_node]]
match = "(马达加斯加|Madagascar)"
replace = "🇲🇬 MG"

[[rename_node]]
match = "(也门|Yemen)"
replace = "🇾🇪 YE"

[[rename_node]]
match = "(塞拉利昂|Sierra Leone)"
replace = "🇸🇱 SL"

[[rename_node]]
match = "(布基纳法索|Burkina Faso)"
replace = "🇧🇫 BF"

[[rename_node]]
match = "(布隆迪|Burundi)"
replace = "🇧🇮 BI"

[[rename_node]]
match = "(马里|Mali)"
replace = "🇲🇱 ML"

[[rename_node]]
match = "(尼日尔|Niger)"
replace = "🇳🇪 NE"

[[rename_node]]
match = "(乍得|Chad)"
replace = "🇹🇩 TD"

[[rename_node]]
match = "(中非共和国|Central African Republic)"
replace = "🇨🇫 CF"

[[rename_node]]
match = "(索马里|Somalia)"
replace = "🇸🇴 SO"

[[rename_node]]
match = "(南苏丹|South Sudan)"
replace = "🇸🇸 SS"

[[rename_node]]
match = "(朝鲜|Korea \\(Democratic People’s Rep\\. of\\))"
replace = "🇰🇵 KP"

[[rename_node]]
match = "(摩纳哥|Monaco)"
replace = "🇲🇨 MC"

[[rename_node]]
match = "(台湾|Taiwan)"
replace = "🇹🇼 TW"
