permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/mihomo-rules.yml
      - mihomo/rules/manifest.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          source .github/scripts/build.sh

          client="mihomo"

          manifest="$client/rules/manifest.yaml"

          source_dir="$client/rules/source"
          merged_dir="$client/rules/merged"
          compiled_dir="$client/rules/compiled"

          install_deps "$client"

          init_rule_dirs "$client"

          download_rules "$manifest" "$source_dir"

          while IFS=$'\t' read -r name type; do
            merged_temp=$(mktemp)
            merged_file="$merged_dir/$name.yaml"

            extract_rules "$source_dir/$name" "$merged_temp"
            exclude_rules "$manifest" "$name" "$merged_temp"
            include_rules "$manifest" "$name" "$merged_temp"
            sort_rules "$merged_temp"

            echo "payload:" > "$merged_file"

            case $type in
              domain)
                sed 's/^/  - "/; s/$/"/' "$merged_temp" >> "$merged_file"
                mihomo convert-ruleset domain yaml "$merged_file" "$compiled_dir/$name.mrs"
                ;;
              ipcidr)
                sed 's/^/  - /' "$merged_temp" >> "$merged_file"
                mihomo convert-ruleset ipcidr yaml "$merged_file" "$compiled_dir/$name.mrs"
                ;;
              classical)
                sed 's/^/  - /' "$merged_temp" >> "$merged_file"
                ;;
              *)
                exit 1
                ;;
            esac

            rm -f "$merged_temp"
          done < <(yq -r '.rules[] | [.name, .type] | @tsv' "$manifest")

          sync_rules "$client/rules"
