permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/singbox-rules.yml
      - sing-box/rules/manifest.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          source .github/scripts/build.sh
          jq_script=".github/scripts/build-json.jq"

          client="sing-box"

          manifest="$client/rules/manifest.yaml"

          source_dir="$client/rules/source"
          merged_dir="$client/rules/merged"
          compiled_dir="$client/rules/compiled"

          install_deps "$client"

          init_rule_dirs "$client"

          download_rules "$manifest" "$source_dir"

          while IFS=$'\t' read -r name; do
            merged_file="$merged_dir/$name.json"

            exclude=$(yq -o=json ".rules[] | select(.name == \"$name\") | .exclude // []" "$manifest")
            include=$(yq -o=json ".rules[] | select(.name == \"$name\") | .include // []" "$manifest")

            if compgen -G "$source_dir/$name/*.json" > /dev/null; then
              jq -cs "[.[].rules[]]" "$source_dir/$name"/*.json
            else
              echo '[]'
            fi \
              | jq -n \
                  --slurpfile remote /dev/stdin \
                  --argjson exclude "$exclude" \
                  --argjson include "$include" \
                  -f "$jq_script" > "$merged_file"

            sing-box rule-set compile "$merged_file" -o "$compiled_dir/$name.srs"
          done < <(yq -r '.rules[].name' "$manifest")

          sync_rules "$client/rules"
