permissions:
  contents: write

on:
  workflow_dispatch:

  schedule:
    - cron: "0 20 * * *"

  push:
    paths:
      - surge/rules/manifest.yaml
      - .github/workflows/surge-rules.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - run: |
          sudo curl -fsSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - run: |
          rm -rf surge/rules/{source,merged}
          mkdir -p surge/rules/{source,merged}

      - run: |
          yq -r '.rules[].name' surge/rules/manifest.yaml \
            | xargs -n1 -P10 sh -c 'mkdir -p "surge/rules/source/$1"' sh

      - run: |
          yq -r '.rules[] | select(.remote) | .name + " " + (.remote[])' surge/rules/manifest.yaml \
            | xargs -n2 -P10 sh -c 'curl -fsSL "$2" -o "surge/rules/source/$1/${2##*/}"' sh

      - run: |
          for d in surge/rules/source/*; do
            name="${d##*/}"
            outfile="surge/rules/merged/${name}.list"

            tmp="${outfile}.tmp"

            rm -f "$tmp"
            : > "$tmp"

            exclude=$(yq -r ".rules[] | select(.name == \"${name}\") | .exclude[]?" surge/rules/manifest.yaml)
            include=$(yq -r ".rules[] | select(.name == \"${name}\") | .include[]?" surge/rules/manifest.yaml)

            if compgen -G "$d/*.list" > /dev/null; then
              if [ -n "$exclude" ]; then
                grep -hv '^#' "$d"/*.list \
                  | grep -vxFf <(printf '%s\n' "$exclude") \
                  >> "$tmp"
              else
                grep -hv '^#' "$d"/*.list \
                  >> "$tmp"
              fi
            fi

            if [ -n "$include" ]; then
              printf '%s\n' "$include" >> "$tmp"
            fi

            LC_ALL=C sort -u "$tmp" > "$outfile"

            rm -f "$tmp"
          done

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add surge/rules
          git diff --cached --quiet || (
            git commit -m "Updated on $(TZ=Asia/Shanghai date '+%F at %T')"
            git pull --rebase
            git push
          )
