permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - surge/rules/manifest.yaml
      - .github/workflows/surge-rules.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          source .github/scripts/build.sh

          client="surge"

          manifest="$client/rules/manifest.yaml"

          source_dir="$client/rules/source"
          merged_dir="$client/rules/merged"

          install_deps "$client"

          init_rule_dirs "$client"

          download_rules "$manifest" "$source_dir"

          while IFS=$'\t' read -r name; do
            merged_file="$merged_dir/$name.list"

            extract_rules "$source_dir/$name" "$merged_file"
            exclude_rules "$manifest" "$name" "$merged_file"
            include_rules "$manifest" "$name" "$merged_file"
            sort_rules "$merged_file"
          done < <(yq -r '.rules[].name' "$manifest")

          sync_rules "$client/rules"